/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "parser_tester.hpp"

using namespace roq;
using namespace roq::bitmex;

using namespace std::literals;

using namespace Catch::literals;

using value_type = json::Instrument;

// note! truncated
TEST_CASE("simple", "[json_instrument]") {
  auto const message = R"({)"
                       R"("table":"instrument",)"
                       R"("action":"partial",)"
                       R"("keys":["symbol"],)"
                       R"("types":{)"
                       R"("symbol":"symbol",)"
                       R"("rootSymbol":"symbol",)"
                       R"("state":"symbol",)"
                       R"("typ":"symbol",)"
                       R"("listing":"timestamp",)"
                       R"("front":"timestamp",)"
                       R"("expiry":"timestamp",)"
                       R"("settle":"timestamp",)"
                       R"("listedSettle":"timestamp",)"
                       R"("relistInterval":"timespan",)"
                       R"("positionCurrency":"symbol",)"
                       R"("underlying":"symbol",)"
                       R"("quoteCurrency":"symbol",)"
                       R"("underlyingSymbol":"symbol",)"
                       R"("reference":"symbol",)"
                       R"("referenceSymbol":"symbol",)"
                       R"("calcInterval":"timespan",)"
                       R"("publishInterval":"timespan",)"
                       R"("publishTime":"timespan",)"
                       R"("maxOrderQty":"long",)"
                       R"("maxPrice":"float",)"
                       R"("lotSize":"long",)"
                       R"("tickSize":"float",)"
                       R"("multiplier":"long",)"
                       R"("settlCurrency":"symbol",)"
                       R"("underlyingToPositionMultiplier":"long",)"
                       R"("underlyingToSettleMultiplier":"long",)"
                       R"("quoteToSettleMultiplier":"long",)"
                       R"("isQuanto":"boolean",)"
                       R"("isInverse":"boolean",)"
                       R"("initMargin":"float",)"
                       R"("maintMargin":"float",)"
                       R"("riskLimit":"long",)"
                       R"("riskStep":"long",)"
                       R"("limit":"float",)"
                       R"("taxed":"boolean",)"
                       R"("deleverage":"boolean",)"
                       R"("makerFee":"float",)"
                       R"("takerFee":"float",)"
                       R"("settlementFee":"float",)"
                       R"("fundingBaseSymbol":"symbol",)"
                       R"("fundingQuoteSymbol":"symbol",)"
                       R"("fundingPremiumSymbol":"symbol",)"
                       R"("fundingTimestamp":"timestamp",)"
                       R"("fundingInterval":"timespan",)"
                       R"("fundingRate":"float",)"
                       R"("indicativeFundingRate":"float",)"
                       R"("rebalanceTimestamp":"timestamp",)"
                       R"("rebalanceInterval":"timespan",)"
                       R"("prevClosePrice":"float",)"
                       R"("limitDownPrice":"float",)"
                       R"("limitUpPrice":"float",)"
                       R"("prevTotalVolume":"long",)"
                       R"("totalVolume":"long",)"
                       R"("volume":"long",)"
                       R"("volume24h":"long",)"
                       R"("prevTotalTurnover":"long",)"
                       R"("totalTurnover":"long",)"
                       R"("turnover":"long",)"
                       R"("turnover24h":"long",)"
                       R"("homeNotional24h":"float",)"
                       R"("foreignNotional24h":"float",)"
                       R"("prevPrice24h":"float",)"
                       R"("vwap":"float",)"
                       R"("highPrice":"float",)"
                       R"("lowPrice":"float",)"
                       R"("lastPrice":"float",)"
                       R"("lastPriceProtected":"float",)"
                       R"("lastTickDirection":"symbol",)"
                       R"("lastChangePcnt":"float",)"
                       R"("bidPrice":"float",)"
                       R"("midPrice":"float",)"
                       R"("askPrice":"float",)"
                       R"("impactBidPrice":"float",)"
                       R"("impactMidPrice":"float",)"
                       R"("impactAskPrice":"float",)"
                       R"("hasLiquidity":"boolean",)"
                       R"("openInterest":"long",)"
                       R"("openValue":"long",)"
                       R"("fairMethod":"symbol",)"
                       R"("fairBasisRate":"float",)"
                       R"("fairBasis":"float",)"
                       R"("fairPrice":"float",)"
                       R"("markMethod":"symbol",)"
                       R"("markPrice":"float",)"
                       R"("indicativeSettlePrice":"float",)"
                       R"("settledPriceAdjustmentRate":"float",)"
                       R"("settledPrice":"float",)"
                       R"("instantPnl":"boolean",)"
                       R"("minTick":"float",)"
                       R"("fundingBaseRate":"float",)"
                       R"("fundingQuoteRate":"float",)"
                       R"("timestamp":"timestamp")"
                       R"(},)"
                       R"("filter":{},)"
                       R"("data":[{)"
                       R"("symbol":".BPENGUT_NEXT",)"
                       R"("rootSymbol":"PENGU",)"
                       R"("state":"Unlisted",)"
                       R"("typ":"MRCXXX",)"
                       R"("underlying":"PENGU",)"
                       R"("quoteCurrency":"USDT",)"
                       R"("underlyingSymbol":"PENGUT=",)"
                       R"("reference":"BMI",)"
                       R"("referenceSymbol":".BPENGUT_NEXT",)"
                       R"("publishInterval":"2000-01-01T00:01:00.000Z",)"
                       R"("tickSize":1.0E-6,)"
                       R"("isQuanto":false,)"
                       R"("isInverse":false,)"
                       R"("taxed":false,)"
                       R"("deleverage":false,)"
                       R"("prevPrice24h":0.02841,)"
                       R"("lastPrice":0.02781,)"
                       R"("lastChangePcnt":-0.0211,)"
                       R"("hasLiquidity":false,)"
                       R"("markMethod":"LastPrice",)"
                       R"("markPrice":0.02781,)"
                       R"("instantPnl":false,)"
                       R"("timestamp":"2025-09-30T05:50:00.000Z")"
                       R"(},{)"
                       R"("symbol":"TRXUSDT",)"
                       R"("rootSymbol":"TRX",)"
                       R"("state":"Open",)"
                       R"("typ":"FFWCSX",)"
                       R"("listing":"2023-11-07T04:00:00.000Z",)"
                       R"("front":"2023-11-07T04:00:00.000Z",)"
                       R"("positionCurrency":"TRX",)"
                       R"("underlying":"TRX",)"
                       R"("quoteCurrency":"USDT",)"
                       R"("underlyingSymbol":"TRXT=",)"
                       R"("reference":"BMEX",)"
                       R"("referenceSymbol":".BTRXT",)"
                       R"("maxOrderQty":1000000000,)"
                       R"("maxPrice":1000.0,)"
                       R"("lotSize":100,)"
                       R"("tickSize":1.0E-5,)"
                       R"("multiplier":100000,)"
                       R"("settlCurrency":"USDt",)"
                       R"("underlyingToPositionMultiplier":10,)"
                       R"("quoteToSettleMultiplier":1000000,)"
                       R"("isQuanto":false,)"
                       R"("isInverse":false,)"
                       R"("initMargin":0.03,)"
                       R"("maintMargin":0.015,)"
                       R"("riskLimit":1000000000000,)"
                       R"("riskStep":1000000000000,)"
                       R"("taxed":true,)"
                       R"("deleverage":true,)"
                       R"("makerFee":5.0E-4,)"
                       R"("takerFee":5.0E-4,)"
                       R"("settlementFee":0.0,)"
                       R"("fundingBaseSymbol":".TRXBON8H",)"
                       R"("fundingQuoteSymbol":".USDTBON8H",)"
                       R"("fundingPremiumSymbol":".TRXUSDTPI8H",)"
                       R"("fundingTimestamp":"2025-09-30T12:00:00.000Z",)"
                       R"("fundingInterval":"2000-01-01T08:00:00.000Z",)"
                       R"("fundingRate":1.0E-4,)"
                       R"("indicativeFundingRate":1.0E-4,)"
                       R"("prevClosePrice":0.333489,)"
                       R"("prevTotalVolume":606292000,)"
                       R"("totalVolume":606292000,)"
                       R"("volume":0,)"
                       R"("volume24h":4949200,)"
                       R"("prevTotalTurnover":15121969746500,)"
                       R"("totalTurnover":15121969746500,)"
                       R"("turnover":0,)"
                       R"("turnover24h":164882852700,)"
                       R"("homeNotional24h":494920.0,)"
                       R"("foreignNotional24h":164882.8527,)"
                       R"("prevPrice24h":0.33584,)"
                       R"("vwap":0.3331506,)"
                       R"("highPrice":0.33666,)"
                       R"("lowPrice":0.33178,)"
                       R"("lastPrice":0.33647,)"
                       R"("lastPriceProtected":0.33647,)"
                       R"("lastTickDirection":"MinusTick",)"
                       R"("lastChangePcnt":0.0032,)"
                       R"("bidPrice":0.33591,)"
                       R"("midPrice":0.336105,)"
                       R"("askPrice":0.3363,)"
                       R"("impactBidPrice":0.335718,)"
                       R"("impactMidPrice":0.336155,)"
                       R"("impactAskPrice":0.3365969,)"
                       R"("hasLiquidity":true,)"
                       R"("openInterest":23527900,)"
                       R"("openValue":791610312240,)"
                       R"("fairMethod":"FundingRate",)"
                       R"("fairBasisRate":0.1095,)"
                       R"("fairBasis":2.6E-5,)"
                       R"("fairPrice":0.336456,)"
                       R"("markMethod":"FairPrice",)"
                       R"("markPrice":0.336456,)"
                       R"("indicativeSettlePrice":0.33643,)"
                       R"("instantPnl":true,)"
                       R"("minTick":1.0E-6,)"
                       R"("fundingBaseRate":3.0E-4,)"
                       R"("fundingQuoteRate":6.0E-4,)"
                       R"("timestamp":"2025-09-30T05:50:01.000Z")"
                       R"(})"
                       R"(])"
                       R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.table == json::Table::INSTRUMENT);
    CHECK(obj.action == json::Action::PARTIAL);
    REQUIRE(std::size(obj.data) == 2);
    CHECK(obj.data[0].symbol == ".BPENGUT_NEXT");
    CHECK(obj.data[1].symbol == "TRXUSDT");
  };
  ParserTester<value_type>::dispatch(helper, message, 8192, 1);
}
