symbols = [
  "BTC-.*",
  "ETH-.*",
]

[order_templates]

  [order_templates.default]
  self_trade_prevention = 'D'

[accounts]

  [accounts.A1]
  master = true
  login = "YOUR_COINBASE_PRO_API_KEY_GOES_HERE"
  password = "YOUR_COINBASE_PRO_PASSPHRASE_GOES_HERE"
  secret = "YOUR_COINBASE_PRO_SECRET_GOES_HERE"
  symbols = [ "BTC-.*", "ETH-.*" ]

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "BTC-USD" ]
  monitor_period_secs = 60
  ban_period_secs = 300
  request_limit = 10
