symbols = ".*"

[accounts]

  [accounts.A1]
  master = true
  login = "GwbEeMsXE4gHEmw4l0MoP4Xb"
  secret = "C8mgDnyw6gVjqRmCDzKQl8sxz5I6zUqiiA14s5U4kJulXRDC"
  symbols = ".*"

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "XBTUSD" ]

[rate_limits]

  [rate_limits.global]
    type = "ORDER_ACTION"
    aggregate = true
    request_limit = 100
    monitor_period = "10s"
    ban_period = "5min"

  [rate_limits.A1]
    type = "CREATE_ORDER"
    account = "A.*"
    request_limit = 30
    monitor_period = "1s"
    ban_period = "5min"

  [rate_limits.market_maker]
    type = "CREATE_ORDER"
    user = [ "trader" ]
    request_limit = 20
    monitor_period = "200ms"
    ban_period = "5min"
