symbols = ".*"

[accounts]

  [accounts.A1]
  master = true
  login = "_UwQLvb_YZtdY_W2uub4Ecax"
  secret = "d1BmhI2QcgnzNzU8y9YZqYpCffYXKg-EXWujke56btbGRCSs"
  symbols = ".*"

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "XBTUSD" ]
  monitor_period_secs = 60
  ban_period_secs = 300
  request_limit = 10
